[package]
name = "rustil"
version = "0.1.0"
authors = ["Shintaro Kaneko"]
license = "MIT"
description = "RusTIL = Rust + Today I Learned"
repository = "https://github.com/kaneshin/rustil"
readme = "README.md"
edition = "2018"

[dependencies]
